# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [1]:
# Import pandas
import pandas as  pd

In [2]:
# Create a series of three different colours
Colors = pd.Series(["Red","Blue","Green"])

In [3]:
# View the series of different colours
Colors

0      Red
1     Blue
2    Green
dtype: object

In [4]:
# Create a series of three different car types and view it
Cars_Model = pd.Series(["BMW","TOYOTA","FARARI"])

In [5]:
# Combine the Series of cars and colours into a DataFrame
cars = pd.DataFrame({"Colors":Colors,"Cars_Model":Cars_Model})
cars

  Colors Cars_Model
0    Red        BMW
1   Blue     TOYOTA
2  Green     FARARI

In [17]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("car-sales.csv")
car_sales

FileNotFoundError: ignored

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [7]:
# Export the DataFrame you created to a .csv file
car_sales.to_csv("new_car_sales.csv")

NameError: ignored

In [8]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

NameError: ignored

In [9]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

NameError: ignored

In [ ]:
# Get information about your DataFrame using info()
car_sales.info()

What does it show you?

In [ ]:
# Create a Series of different numbers and find the mean of them
mean_data = pd.Series([1,13,234,456,567])
mean_data.mean()

In [ ]:
# Create a Series of different numbers and find the sum of them
sum = pd.Series([1,13,234,456,567])
sum.sum()

In [ ]:
# List out all the column names of the car sales DataFrame
car_sales.columns

In [ ]:
# Find the length of the car sales DataFrame
len(car_sales)

In [ ]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head(5)

In [ ]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

In [10]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail(5)

NameError: ignored

In [ ]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

In [ ]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Notice how they're the same? Why do you think this is? 

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [11]:
# Select the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

NameError: ignored

In [12]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer (KM)"].mean()

NameError: ignored

In [ ]:
# Select the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales["Odometer (KM)"] > 100000]

In [ ]:
# Create a crosstab of the Make and Doors columns
pd.crosstab(car_sales.Make,car_sales.Doors)

In [ ]:
# Group columns of the car sales DataFrame by the Make column and find the average
car_sales.groupby("Make").mean()

In [ ]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
# Create a histogram of the Odometer column using hist()
car_sales["Odometer (KM)"].hist()

In [ ]:
# Try to plot the Price column using plot()
car_sales
car_sales["Price"].replace('[\$\,\.]', '',regex=True).astype(int).plot()

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [13]:
# Remove the punctuation from price column
car_sales
car_sales.Price=car_sales["Price"].replace('[\$\,\.]', '',regex=True).astype(int)

NameError: ignored

In [14]:
# Check the changes to the price column
car_sales.Price

NameError: ignored

In [ ]:
# Remove the two extra zeros at the end of the price column
car_sales.Prices = car_sales.Price.astype(str).str[:-2]

In [15]:
# Check the changes to the Price column
car_sales.Prices

NameError: ignored

In [ ]:
# Change the datatype of the Price column to integers
car_sales.Prices.astype(int)

In [ ]:
# Lower the strings of the Make column
car_sales.Make.str.lower()

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [ ]:
# Make lowering the case of the Make column permanent
car_sales["Make"] = car_sales.Make.str.lower()

In [ ]:
# Check the car sales DataFrame
car_sales

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [ ]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")
car_sales_missing_data = pd.read_csv("car-sales-missing-data.csv")

# Check out the new DataFrame
car_sales_missing_data

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [16]:
# Fill the Odometer column missing values with the mean of the column inplace
car_sales_missing_data["Odometer"].fillna(car_sales_missing_data['Odometer'].mean(),inplace=True)

NameError: ignored

In [ ]:
# View the car sales missing DataFrame and verify the changes
car_sales_missing_data

In [ ]:
# Remove the rest of the missing data inplace
car_sales_missing_data.dropna(inplace=True)

In [ ]:
# Verify the missing values are removed by viewing the DataFrame
car_sales_missing_data

We'll now start to add columns to our DataFrame.

In [ ]:
# Create a "Seats" column where every row has a value of 5
car_sales_missing_data["Seats"]=5
car_sales_missing_data

In [ ]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
car_sales_missing_data["Engine Size"] = [1.3,2,2.5,3.4,4.3,4.5]
car_sales_missing_data

In [ ]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame
car_sales_missing_data["car per kilometer"] = car_sales_missing_data["Odometer"]/100
car_sales_missing_data

In [ ]:
# Remove the last column you added using .drop()
car_sales_missing_data.drop("car per kilometer",axis=1,inplace=True)

In [ ]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable
car_sales_missing_data= car_sales_missing_data.sample(frac=1)
car_sales_missing_data

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [ ]:
# Reset the indexes of the shuffled DataFrame
car_sales_missing_data.reset_index(drop=True,inplace=True)
car_sales_missing_data

Notice the index numbers have been changed to have order (start from 0).

In [ ]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame
car_sales_missing_data.Odometer = car_sales_missing_data.Odometer.apply(lambda x: x/1.6)
car_sales_missing_data

In [ ]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers
car_sales_missing_data.rename(columns = {"Odometer":"Kilometer"},inplace=True)
car_sales_missing_data

In [19]:
cars

  Colors Cars_Model
0    Red        BMW
1   Blue     TOYOTA
2  Green     FARARI

## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html). 

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.

In [20]:
cars

  Colors Cars_Model
0    Red        BMW
1   Blue     TOYOTA
2  Green     FARARI

IndexError: ignored